### PR TITLE
Fix bug when using 'key' or 'value' variables

### LINKED ISSUE #344: Bug when using `value` or `key` variable
There's a bug when using the `value` or `key` variable in combination with `apply_for` loops. I want to loop over a dictionary or list and then use the `key` or `value` to access items.

Here's an example service
```yml
...
  - name: Check BGP VRF- + value.description
    type: Service
    display_name: Check BGP VRF- + value.description
    file: zones.d/main/services/services.conf
    apply: true
    apply_for: key => value in host.vars.nb.config.bgp_sessions.vrf
    imports:
      - generic-service
    check_command: check_nwc_health
    assign:
      - host.vars.nb.platform == slx-os
    vars:
      check_nwc_mode: bgp-peer-status
      snmp_v3_context: key
...
```

here's the rendered Icinga2 object. Please note the quotes around `value.description`.
```
apply Service for (key => value in host.vars.nb.config.bgp_sessions.vrf)  {
  import "generic-service"

  display_name = "Check BGP VRF-" + "value.description"
  check_command = "check_nwc_health"
  assign where host.vars.nb.platform == "slx-os"
  vars.check_nwc_mode = "bgp-peer-status"
  vars.snmp_v3_context = key
}
```

These quotes need to be removed so that the GUI correctly displays the monitored services.

### PR DESCRIPTION
**Pull request by lucagubler**
Fix #344

### CODE REVIEW

**Comment by Donien** [comment]
Hi,

if we do it like this (adding `key` and `value` statically), we can **only** use `apply_for: key => value in host.vars.some_dict`.

This means `apply_for: k => v in host.vars.some_dict` would not have the same effect.  

I have not yet looked at the specific code but maybe something like this could work:
- Is apply for:
  - regex `"(\w+) => (\w+)"` against apply_for string (`k => v in host.vars.some_dict`, `key => value in host.vars.some_dict`, etc.)
  - add `\1` and `\2` (both captured groups) to the *do-not-quote-this-string-list*
  - ...
  - profit?

**Comment by lucagubler** [comment]
@Donien It was a bit tricky but I think now it should work as expected. Now you can use any names for key/value inside of the apply_for loop
- `apply_for: k => v in host.vars.my_dict`
- `apply_for: key => value in host.vars.my_dict`
- `apply_for: foo => bar in host.vars.my_dict`

**Review by Donien — APPROVED** [review]
This looks good to me. Haven't found any weird behavior.

Would you please just add a changelog.

**changelogs/fragments/fix_issue_344_allow_loop_variable_usage.yml**:

```yaml
minor_changes:
  - Allow for usage of loop variables from :code:`apply_for` within object - Thanks @lucagubler (#344)
```

**Comment by Donien** [comment]
Thanks again :)

**Pull request merged**
