### PR TITLE
Fixed typo in api.yml

### PR DESCRIPTION
**Pull request by atrestis**
I am currently using ansible-collection-icinga to programmatically provision icinga and came across this typo. Thought it would be helpful :)

### CODE REVIEW

**Review by martialblog — APPROVED** [review]

**Comment by atrestis** [comment]
Is it possible to rerun the cla verification?

**Comment by martialblog** [comment]
Yes. We'll take care of it

@bobapple Ping :ping_pong:

**Comment by bobapple** [comment]
@cla-bot check

**Comment by martialblog** [comment]
Thanks for the PR!

**Pull request merged**
