### PR TITLE
Feature folders inside files

### PR DESCRIPTION
**Pull request by fscaptain**
enables the use of a folder structure within files/ for more clarity and structure for custom  configuration files.

### CODE REVIEW

**Comment by fscaptain** [comment]
> Thank you for your pull request. Before we can look at it, you'll need to sign a Contributor License Agreement (CLA).
> 
> **Please follow instructions at https://icinga.com/company/contributor-agreement to sign the CLA.**
> 
> After that, please reply here with a comment and we'll verify.
> 
> Contributors that have not signed yet: @fscaptain
> 
>     * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Please [contact us](https://icinga.com/company/contact/) if you think this is the case.
> 
>     * If you signed the CLA as a corporation, your GitHub username may not have been submitted to us. Please reach out to the responsible person in your organization.

CLA signed.

**Comment by fscaptain** [comment]
CLA signed.

**Comment by bobapple** [comment]
@cla-bot check

**Comment by mkayontour** [comment]
Hi, thanks for the PR. This seems to be a reasonable way to structure files in the files directory. 

Can you add a changelog fragments as described in the following document? [CONTRIBUTING.md](https://github.com/Icinga/ansible-collection-icinga/blob/main/CONTRIBUTING.md)

**Comment by fscaptain** [comment]
> Hi, thanks for the PR. This seems to be a reasonable way to structure files in the files directory.
> 
> Can you add a changelog fragments as described in the following document? [CONTRIBUTING.md](https://github.com/Icinga/ansible-collection-icinga/blob/main/CONTRIBUTING.md)

Done.

**Comment by mkayontour** [comment]
Hi, @Donien implemented the feature in a different PR. Can you check if this will solve your issue? 

This allows you to structure your files within the "files" directory how you want. 
https://github.com/Icinga/ansible-collection-icinga/pull/313

**Comment by fscaptain** [comment]
Hi,

the implementation from @Donien will solve this.

**Comment by mkayontour** [comment]
Thanks, will be available with the next version. Closed

**Pull request closed without merging**
