### PR TITLE
Use lookup plugin to load icinga2_objects to support existing vars (#138)

### PR DESCRIPTION
**Pull request by martin-gudmundson**

### CODE REVIEW

**Comment by martin-gudmundson** [comment]
signed

**Comment by bobapple** [comment]
@cla-bot check

**Review by martialblog — APPROVED** [review]
LGTM

**Comment by martialblog** [comment]
@martin-gudmundson Thanks for the PR and for adding the changelog

**Comment by mkayontour** [comment]
The first "vars" task is obsolete with this solution. You can remove the task completely `name: - name: collect all config objects for myself`. Otherwise we will generate the same data twice and the lookup also includes the hostvars. 

After that I will happily merge your PR. Thank you :)

**Comment by martin-gudmundson** [comment]
@mkayontour Are you sure?

As I understand it, the first task you mention is aggregating object configurations from the hosts file, including from other hosts that has objects defined for the current host.

These would not be included if the first task is not run. And I see no duplicate issues either from my tests where objects are included more than once in the `tmp_objects` variable.

Example:
**hosts.yaml**
```
---
    all:
      children:
        monitor_master:
          hosts:
            master.example.com:
              icinga2_objects:
                master.example.com:
                  - type: Endpoint
                    file: zones.conf
                    name: master.example.com
                    host: 127.0.0.1
        monitored_hosts:
          hosts:
            agent1.example.com:
              icinga2_objects:
                master.example.com:
                  - type: Endpoint
                    file: zones.conf
                    name: agent1.example.com
                    host: 1.2.3.4
```

deploy-playbook.yaml
```
- name: Monitoring server master installation.
  hosts: monitor_master
    ...
    icinga2_objects:
      master.example.com:
        - type: Host
          file: zones.d/main/hosts/hosts.conf
          name: agent1.example.com

  roles:
    - icinga.icinga.repos
    - icinga.icinga.icinga2
```

So it would be a breaking change relative to current functionality to remove that task. It would mean that the resulting `tmp_objects` would only include the object 

```
[{
    "name": "agent1.example.com",
    "file": "zones.d/main/hosts/hosts.conf",
    "type": "Host",
}]
```

**Comment by mkayontour** [comment]
hi, I'm sorry for the confusion @martin-gudmundson. You are right, this would break the current function to define monitoring data at the agent host variables level. 

I've tested again and it works flawlessly. I'll merge right away.

**Pull request merged**
