### PR TITLE
add become to tasks and handlers

### PR DESCRIPTION
**Pull request by svenkalinowski**
Added 'become: true' to every tasks where required.
Tested successfully on Debian bookworm.

### CODE REVIEW

**Comment by svenkalinowski** [comment]
Successfully merging this pull request may close these issues: #337

**Comment by mkayontour** [comment]
I would rather not add become to every action. There might someone using a privileged user which then always does an extra "become" for every task. 
What's with become on the playbook level?

**Comment by Donien** [comment]
Most of the Collection is made specifically to do **administrative** work. I, currently, don't see any spot where we'd need to distinguish between `run as root` and `do this as a normal user`.

If you don't want to use `become` for your whole play(book), you can also resort to another way of calling a role.

```yaml
- name: Play
  become: false
  hosts: all
  roles:
    - name: icinga.icinga.icinga2
      become: true
    - some_other_role_without_become
    - name: explicit_no_become
      become: false
```

> Switching the "global" `become` and the role's `become` also works just fine.

**Comment by mkayontour** [comment]
I'll document the issue and give the example if someone doesn't now where the become can be configured. Closed

**Pull request closed without merging**
