### PR TITLE
Rename manage_schema_pgsql.yml to manage_schema_psql.yml

### PR DESCRIPTION
**Pull request by fl0wx**
Fixed manage_schema naming for postgres to match icinga database_type name.

### CODE REVIEW

**Comment by mkayontour** [comment]
Hi I don't really understand die Issue. The type should be "pgsql". 
https://github.com/Icinga/icingadb/blob/main/doc/03-Configuration.md#database-configuration

**Comment by fl0wx** [comment]
sorry my fault, misread and then misspelled the type. sorry for that. ill close the pr

**Comment by mkayontour** [comment]
No worries, thanks anyway for contributing. Is it unclear in the documentation?

**Comment by fl0wx** [comment]
no, documentation was clear, just didnt read correctly

**Pull request closed without merging**
