### PR TITLE
WIP: add Suse support for the repos role

### PR DESCRIPTION
**Pull request by johanneskastl**
I prefer to use the copy module instead of `community.general.zypper_repository`, as the latter does not support the check mode.

I found no testing repository for Suse/openSUSE, only stable and snapshot?

### CODE REVIEW

**Comment by bobapple** [comment]
@cla-bot check

**Comment by johanneskastl** [comment]
> Should I add a collections/requirements.yml or a line in the galaxy.yml to make this visible?

Any opinions?

**Comment by mocdaniel** [comment]
> I found no testing repository for Suse/openSUSE, only stable and snapshot?

That's correct, there seems to only exist stable and snapshot.

> Should I add a collections/requirements.yml or a line in the galaxy.yml to make this visible?

I added my opinion and tagged other maintainers in the corresponding draft PR.

**Comment by johanneskastl** [comment]
> > I found no testing repository for Suse/openSUSE, only stable and snapshot?
> 
> That's correct, there seems to only exist stable and snapshot.

OK, then I would remove the (unused) parts regarding testing.

**Comment by mkayontour** [comment]
Work continues in PR https://github.com/Icinga/ansible-collection-icinga/pull/273.

**Pull request closed without merging**
